spring:
  application:
    name:
      hello-service
#  datasource:
#    username: root
#    password: pass@word1

server:
  port:
    8051
        
    
eureka:
  client:
  #to regsiter this service Service Discovery
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    